# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Dasoraster
                                 A QGIS plugin
 Herramientas para trabajar con rastes dasométricos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-27
        copyright            : (C) 2024 by Jose Bengoa
        email                : dasonoma@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Dasoraster class from file Dasoraster.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dasoraster import Dasoraster
    return Dasoraster(iface)
